#!/usr/bin/env bash
# Auto-update GLM model version in oneshot and shell config

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/models.env"

# Get current pinned version
if [[ -f "$ENV_FILE" ]]; then
  source "$ENV_FILE"
  CURRENT="${ZAI_MODEL_PIN:-unknown}"
else
  CURRENT="unknown"
fi

# Get latest from Hugging Face (fallback to current if detection fails)
LATEST=$("$SCRIPT_DIR/detect-latest-glm.sh" 2>/dev/null) || LATEST="$CURRENT"

if [[ "$LATEST" == "$CURRENT" ]]; then
  echo "✓ GLM: $CURRENT (up to date)"
  exit 0
fi

# Auto-update: Update models.env in oneshot repo
echo "⚠️  GLM: auto-updating $CURRENT → $LATEST"

# Update models.env
sed -i.bak "s/^ZAI_MODEL_PIN=.*/ZAI_MODEL_PIN=$LATEST/" "$ENV_FILE"
rm -f "${ENV_FILE}.bak"

# Update shell config
if [[ -n "${ZSH_VERSION:-}" ]]; then
  SHELLRC="$HOME/.zshrc"
else
  SHELLRC="$HOME/.bashrc"
fi

if [[ -f "$SHELLRC" ]]; then
  # Update GLM_MODEL in shell config (new format)
  if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS requires -i '' for in-place editing
    sed -i '' "s/^GLM_MODEL=.*/GLM_MODEL=\"$LATEST\"/" "$SHELLRC" 2>/dev/null || true
    # Also update old format: ${ZAI_MODEL:-glm-X.X} default
    sed -i '' "s/\${ZAI_MODEL:-glm-[0-9.]*}/\${ZAI_MODEL:-$LATEST}/" "$SHELLRC" 2>/dev/null || true
  else
    sed -i "s/^GLM_MODEL=.*/GLM_MODEL=\"$LATEST\"/" "$SHELLRC" 2>/dev/null || true
    # Also update old format: ${ZAI_MODEL:-glm-X.X} default
    sed -i "s/\${ZAI_MODEL:-glm-[0-9.]*}/\${ZAI_MODEL:-$LATEST}/" "$SHELLRC" 2>/dev/null || true
  fi
fi

# Commit and push models.env change
cd "$SCRIPT_DIR/.."
if git diff --quiet "$ENV_FILE" 2>/dev/null; then
  :  # No changes
else
  git add "$ENV_FILE" 2>/dev/null || true
  git commit -m "chore: Auto-update GLM model to $LATEST

- Auto-generated by heartbeat
- Machine: $(hostname)" 2>/dev/null || true
  git push origin master 2>/dev/null || true
fi

echo "✓ GLM: updated to $LATEST (source ~/.bashrc or source ~/.zshrc to apply)"
exit 0
