#!/usr/bin/env bash
# Wire up the janitor as a global service for all projects on this machine.
# Run once on each machine (oci-dev, homelab, macmini).
#
# What this does:
#   1. Creates ~/.config/oneshot/ with env.sh (ONESHOT_DIR) and janitor_providers.yaml
#   2. Installs the cron job (hourly, via install-janitor-cron.sh)
#
# Usage:
#   bash scripts/setup-global.sh

set -euo pipefail

ONESHOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="$HOME/.config/oneshot"

echo "Setting up global janitor from: $ONESHOT_DIR"

# 1. Create config dir
mkdir -p "$CONFIG_DIR"

# 2. Write env.sh — sourced by all hooks to find oneshot
cat > "$CONFIG_DIR/env.sh" << EOF
# Auto-generated by scripts/setup-global.sh — do not edit manually.
export ONESHOT_DIR="$ONESHOT_DIR"
EOF
echo "  Written: $CONFIG_DIR/env.sh  (ONESHOT_DIR=$ONESHOT_DIR)"

# 3. Copy janitor_providers.yaml if not already customised
if [ ! -f "$CONFIG_DIR/janitor_providers.yaml" ]; then
  cp "$ONESHOT_DIR/config/janitor_providers.yaml" "$CONFIG_DIR/janitor_providers.yaml"
  echo "  Written: $CONFIG_DIR/janitor_providers.yaml  (edit this to set API keys / budget)"
else
  echo "  Kept:    $CONFIG_DIR/janitor_providers.yaml  (already exists, not overwritten)"
fi

# 4. Install cron
bash "$ONESHOT_DIR/scripts/install-janitor-cron.sh"

echo ""
echo "Done. Next steps:"
echo "  1. Add API keys to $CONFIG_DIR/janitor_providers.yaml"
echo "     (or set OPENROUTER_API_KEY / QWEN_API_KEY / GEMINI_API_KEY in your shell)"
echo "  2. Test: python3 -m core.janitor.cron --once --verbose"
echo "  3. View cross-project report: python3 -m core.janitor.harvest --report"
